---
- hosts: landpage
  gather_facts: no
  vars:
      ansible_host_key_checking: false

  tasks:
    - name: Change domain name
      shell: grep {{ OUT }} -rl /landpage/{{ Group }}/{{ DIRNAME }} | xargs sed -i "s#{{ OUT }}#{{ NEW }}#g"


- hosts: 192.168.21.6
  gather_facts: no
  vars:
      ansible_host_key_checking: false
  tasks:
    - name: Change domain name FTP
      shell: grep {{ OUT }} -rl /home/ops/ftpdata/{{ Group }}/{{ DIRNAME }} | xargs sed -i "s#{{ OUT }}#{{ NEW }}#g"
